export {default as Hero} from './Hero'
export {default as WhoWeAre} from './WhoWeAre'
export {default as Services} from './ServicePackages'
export {default as OurWork} from './OurWork'
export {default as OurClients} from './OurClients'
export {default as WeAreWhatYouNeed} from './WeAreWhatYouNeed'
